/* The following code was generated by JFlex 1.4.1 on 3/2/09 4:18 PM */

/***** JFlex specification for Arc *****/

package com.bitbakery.plugin.arc.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.bitbakery.plugin.arc.lexer.ArcTokenTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 3/2/09 4:18 PM from the specification file
 * <tt>src/com/bitbakery/plugin/arc/lexer/arc.flex</tt>
 */
public class _ArcLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\14\1\33"+
    "\1\5\3\14\1\56\1\34\1\35\1\14\1\12\1\57\1\12\1\13"+
    "\1\14\1\10\11\7\1\61\1\4\1\14\1\54\2\14\1\60\1\63"+
    "\1\14\1\64\1\50\1\11\1\47\1\14\1\52\1\42\2\14\1\43"+
    "\1\62\1\41\1\46\1\14\1\44\2\14\1\40\1\45\1\14\1\51"+
    "\3\14\1\36\1\15\1\37\2\14\1\55\1\25\1\30\1\26\1\50"+
    "\1\17\1\47\1\14\1\52\1\22\2\14\1\21\1\62\1\16\1\46"+
    "\1\24\1\44\1\31\1\23\1\27\1\32\1\14\1\20\3\14\1\0"+
    "\1\6\1\0\1\53\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\3\3\3\1\1\4\1\1\1\5\4\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\3\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\1\2\0\2\22"+
    "\1\1\1\0\4\4\3\1\1\23\2\7\1\1\1\24"+
    "\1\1\1\25\1\26\1\1\3\0\1\1\5\27\1\30"+
    "\1\1\1\31\1\1\1\32\1\33\2\34\1\0\1\35"+
    "\4\0\1\36\1\1\1\35\3\0\1\37\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\65\0\237\0\324\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u013e"+
    "\0\u02e6\0\65\0\65\0\65\0\65\0\u031b\0\u0350\0\u0385"+
    "\0\65\0\u013e\0\65\0\65\0\u03ba\0\65\0\u03ef\0\237"+
    "\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\u013e\0\u05cc\0\u0601\0\u0636\0\u013e\0\u066b\0\65\0\u06a0"+
    "\0\u013e\0\u06d5\0\u013e\0\65\0\u070a\0\u048e\0\u073f\0\u0774"+
    "\0\u07a9\0\65\0\u07de\0\u0813\0\u0848\0\u087d\0\u013e\0\u08b2"+
    "\0\u013e\0\u08e7\0\u013e\0\u013e\0\u091c\0\u048e\0\u0951\0\u04c3"+
    "\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u013e\0\u0a5a\0\u0774\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u013e\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\11"+
    "\1\10\1\12\1\13\1\10\1\2\1\14\1\10\1\15"+
    "\1\16\1\17\4\10\1\20\3\10\1\21\1\22\1\23"+
    "\1\24\1\25\1\20\1\14\1\17\1\16\1\26\2\10"+
    "\1\27\1\30\1\15\1\10\1\31\1\32\1\33\1\34"+
    "\1\35\1\10\1\36\1\37\2\10\67\0\1\4\65\0"+
    "\1\40\1\41\60\0\1\41\1\42\1\43\1\41\11\6"+
    "\1\41\15\6\5\41\13\6\1\41\1\6\3\41\1\6"+
    "\1\41\3\6\4\0\2\10\1\44\6\10\1\45\15\10"+
    "\5\0\13\10\1\0\1\10\3\0\1\10\1\0\3\10"+
    "\4\0\11\10\1\0\15\10\5\0\13\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\3\10\2\11\1\46"+
    "\1\10\1\47\1\10\1\0\1\10\1\46\13\10\5\0"+
    "\13\10\1\0\1\10\3\0\1\10\1\0\3\10\4\0"+
    "\3\10\1\50\1\51\4\10\1\0\15\10\5\0\13\10"+
    "\1\0\1\10\3\0\1\10\1\0\3\10\4\0\3\10"+
    "\2\47\4\10\1\0\15\10\5\0\13\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\11\10\1\0\4\10"+
    "\1\52\10\10\5\0\2\10\1\52\10\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\11\10\1\0\4\10"+
    "\1\53\10\10\5\0\2\10\1\53\10\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\5\10\1\54\3\10"+
    "\1\0\1\10\1\54\13\10\5\0\13\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\11\10\1\0\15\10"+
    "\5\0\7\10\1\55\3\10\1\0\1\10\3\0\1\10"+
    "\1\0\3\10\15\21\1\56\15\21\1\57\31\21\4\0"+
    "\11\10\1\0\14\10\1\60\5\0\5\10\1\60\5\10"+
    "\1\0\1\10\3\0\1\10\1\0\3\10\4\0\11\10"+
    "\1\0\1\61\14\10\5\0\1\10\1\61\11\10\1\0"+
    "\1\10\3\0\1\10\1\0\3\10\4\0\5\10\1\62"+
    "\3\10\1\0\1\10\1\62\13\10\5\0\6\10\1\63"+
    "\4\10\1\0\1\10\3\0\1\10\1\0\3\10\60\0"+
    "\1\64\10\0\11\10\1\0\7\10\1\65\5\10\5\0"+
    "\13\10\1\0\1\10\3\0\1\10\1\0\1\10\1\65"+
    "\1\10\1\41\1\42\1\43\62\41\2\0\1\43\1\66"+
    "\1\67\63\0\1\66\1\67\60\0\4\70\2\44\1\71"+
    "\6\44\1\70\15\44\5\70\13\44\1\70\1\44\3\70"+
    "\1\44\1\70\3\44\4\0\11\72\1\0\1\73\4\72"+
    "\1\74\3\72\1\75\1\72\1\76\2\72\4\0\13\72"+
    "\1\0\1\72\3\0\1\72\1\0\3\72\4\0\3\10"+
    "\2\50\1\10\1\50\2\10\1\0\15\10\5\0\13\10"+
    "\1\0\1\10\3\0\1\10\1\0\3\10\4\0\3\10"+
    "\2\47\1\46\3\10\1\0\1\10\1\46\13\10\5\0"+
    "\13\10\1\0\1\10\3\0\1\10\1\0\3\10\4\0"+
    "\3\10\2\50\4\10\1\0\15\10\5\0\13\10\1\0"+
    "\1\10\3\0\1\10\1\0\3\10\4\0\11\10\1\0"+
    "\3\10\1\77\11\10\5\0\3\10\1\77\7\10\1\0"+
    "\1\10\3\0\1\10\1\0\3\10\4\0\11\10\1\0"+
    "\11\10\1\100\3\10\5\0\1\100\12\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\11\10\1\0\11\10"+
    "\1\101\3\10\5\0\1\101\12\10\1\0\1\10\3\0"+
    "\1\10\1\0\3\10\1\21\2\0\62\21\4\0\11\10"+
    "\1\0\15\10\5\0\6\10\1\102\4\10\1\0\1\10"+
    "\3\0\1\10\1\0\3\10\4\0\11\10\1\0\15\10"+
    "\5\0\7\10\1\103\3\10\1\0\1\10\3\0\1\10"+
    "\1\0\3\10\4\0\11\10\1\0\10\10\1\104\4\10"+
    "\5\0\13\10\1\0\1\10\3\0\1\10\1\0\2\10"+
    "\1\104\1\67\1\105\1\106\62\67\6\70\1\107\62\70"+
    "\1\44\1\110\1\71\6\44\1\70\15\44\5\70\13\44"+
    "\1\70\1\44\3\70\1\44\1\70\3\44\17\0\1\111"+
    "\71\0\1\112\65\0\1\113\56\0\1\114\51\0\11\10"+
    "\1\0\15\10\5\0\12\10\1\115\1\0\1\10\3\0"+
    "\1\10\1\0\3\10\4\0\11\10\1\0\11\10\1\116"+
    "\3\10\5\0\1\116\12\10\1\0\1\10\3\0\1\10"+
    "\1\0\3\10\2\0\1\106\1\66\1\67\60\0\5\70"+
    "\1\117\1\107\56\70\20\0\1\120\71\0\1\121\67\0"+
    "\1\72\63\0\1\122\41\0\5\10\1\123\3\10\1\0"+
    "\1\10\1\123\13\10\5\0\13\10\1\0\1\10\3\0"+
    "\1\10\1\0\3\10\21\0\1\124\71\0\1\125\70\0"+
    "\1\126\54\0\1\127\61\0\1\72\76\0\1\130\51\0"+
    "\1\125\64\0\1\72\46\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3127];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\15\1\4\11\3\1\1\11"+
    "\1\1\2\11\1\1\1\11\1\1\2\0\3\1\1\0"+
    "\11\1\1\11\4\1\1\11\1\1\3\0\1\1\1\11"+
    "\14\1\1\0\1\1\4\0\3\1\3\0\1\1\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    StringBuffer string = new StringBuffer();


  public _ArcLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _ArcLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { return COMMA;
          }
        case 32: break;
        case 15: 
          { return QUOTE;
          }
        case 33: break;
        case 22: 
          { return COMMA_AT;
          }
        case 34: break;
        case 18: 
          { return LINE_COMMENT;
          }
        case 35: break;
        case 23: 
          { return CHAR_LITERAL;
          }
        case 36: break;
        case 19: 
          { return IF;
          }
        case 37: break;
        case 2: 
          { return BAD_CHARACTER;
          }
        case 38: break;
        case 8: 
          { return LEFT_PAREN;
          }
        case 39: break;
        case 20: 
          { return FN;
          }
        case 40: break;
        case 14: 
          { return BACKQUOTE;
          }
        case 41: break;
        case 17: 
          { return COMPOSER;
          }
        case 42: break;
        case 24: 
          { return NIL;
          }
        case 43: break;
        case 10: 
          { return LEFT_SQUARE;
          }
        case 44: break;
        case 31: 
          { return QUOTE_KEYWORD;
          }
        case 45: break;
        case 9: 
          { return RIGHT_PAREN;
          }
        case 46: break;
        case 7: 
          { return STRING_LITERAL;
          }
        case 47: break;
        case 21: 
          { return DO;
          }
        case 48: break;
        case 4: 
          { return NUMERIC_LITERAL;
          }
        case 49: break;
        case 29: 
          { return BLOCK_COMMENT;
          }
        case 50: break;
        case 28: 
          { return MULTILINE_COMMENT;
          }
        case 51: break;
        case 25: 
          { return LET;
          }
        case 52: break;
        case 1: 
          { return SYMBOL;
          }
        case 53: break;
        case 26: 
          { return DEF;
          }
        case 54: break;
        case 27: 
          { return MAC;
          }
        case 55: break;
        case 13: 
          { return EQ;
          }
        case 56: break;
        case 12: 
          { return TILDE;
          }
        case 57: break;
        case 5: 
          { return DOT;
          }
        case 58: break;
        case 30: 
          { return WITH;
          }
        case 59: break;
        case 6: 
          { return TRUE;
          }
        case 60: break;
        case 3: 
          { return WHITESPACE;
          }
        case 61: break;
        case 11: 
          { return RIGHT_SQUARE;
          }
        case 62: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
